use super::models::CheckId;
use crate::cli;
use crate::git::login_env;
use crate::git::models::{GitError, GitErrorCode};
use std::path::Path;

/// 由解析到的 PATH 產生 husky init.sh 內容。純函式,可測。
pub fn husky_init_contents(effective_path: &str) -> String {
    format!(
        "# Generated by Vapor doctor: husky sources this file before every git hook\n\
         # to add tool paths missing when launched from the GUI (Finder/Dock).\n\
         export PATH=\"{effective_path}:$PATH\"\n"
    )
}

fn io_error(detail: &str) -> GitError {
    GitError {
        code: GitErrorCode::CommandFailed,
        message: "Doctor fix failed.".to_string(),
        hint: "Check write permissions for ~/.config in your home directory and try again.".to_string(),
        stderr: detail.to_string(),
    }
}

fn fix_husky_init() -> Result<String, GitError> {
    let target = super::husky_init_path().ok_or_else(|| io_error("home dir not found"))?;
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent).map_err(|error| io_error(&error.to_string()))?;
    }
    let resolution = login_env::resolution();
    std::fs::write(&target, husky_init_contents(&resolution.effective_path))
        .map_err(|error| io_error(&error.to_string()))?;
    Ok(format!("Created {}.", target.display()))
}

/// 執行單項自動修正;不可自動修者回 Err。
pub fn apply(id: CheckId, app_binary: &Path) -> Result<String, GitError> {
    match id {
        CheckId::VaporCli => cli::install_cli(app_binary),
        CheckId::HuskyInit => fix_husky_init(),
        CheckId::GitAvailable | CheckId::LoginPath | CheckId::GitLfs => Err(GitError {
            code: GitErrorCode::CommandFailed,
            message: "This item cannot be fixed automatically.".to_string(),
            hint: "Follow the instructions shown for the check to fix it manually.".to_string(),
            stderr: String::new(),
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn husky_contents_export_the_given_path() {
        let contents = husky_init_contents("/opt/homebrew/bin:/Users/u/.bun/bin");
        assert!(contents.contains("export PATH=\"/opt/homebrew/bin:/Users/u/.bun/bin:$PATH\""));
    }

    #[test]
    fn apply_rejects_non_auto_fixable_checks() {
        let error = apply(CheckId::GitAvailable, Path::new("/x")).expect_err("not auto-fixable");
        assert_eq!(error.code, GitErrorCode::CommandFailed);
    }
}
